# This is a basic workflow to help you get started with Actions

name: Update TODO

# Controls when the workflow will run
on:
  # Triggers the workflow on push or workflow_dispatch request events
  push:
    paths:
    - "**.gml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  generate-todo:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Create TODO.md
        run: |
          curl DIR_TO_TODO/todo.py
          python todo.py
        
      - name: Push changes
        run: |
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}/
          
