name: Update TODO

on:
  push:
    paths-ignore: 
      - "**.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-todo:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Create TODO.md
        run: |
          curl -O https://raw.githubusercontent.com/hoverAdev/actions/main/generate-todo/todo.py
          python3 todo.py
        
      - name: Commit and push changes
        run: |
          git commit -a -m "Update TODO.md"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}/
          
