#!/bin/python
"""
todo.py by hoverAdev
This file generates a TODO.md based on files in the working directory.
Directories will be traversed recursively.
Files with todo in the name with be ignored (ex "todo.yml", "TODO.md"
"""

import os

md = open("TODO.md", "w")
md.write("# Found TODOs (Autogenerated)\n")

for (root, dirs, files) in os.walk('.'):
    for file in files:
        rpath = f"{root}/{file}"
        if "todo" in rpath.lower():
            pass
        else:
            f = open(rpath)

            try:
                text = f.read()
                textfile = True
            except:
                textfile = False

            if textfile:
                if "TODO" in text:
                    print(f"## {rpath}")
                    md.write(f"## {rpath}\n")
                    lines = text.splitlines()
                    for line in lines:
                        if "TODO" in line:
                            print(f"* {lines.index(line)} {line}")
                            md.write(f"* {lines.index(line)} {line}\n")
                    print("\n")
                    md.write("\n")
                f.close()

md.close()
