name: Update TODO

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-todo:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Create TODO.md
        run: |
          curl https://raw.githubusercontent.com/hoverAdev/actions/main/generate-todo/todo.py
          python todo.py
        
      - name: Push changes
        run: |
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}/
          
